# Generated by Django 4.2 on 2026-05-15 20:02

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Porcentaje (%)'), ('fixed', 'Monto fijo ($)')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Máximo descuento en pesos (solo para porcentaje)', max_digits=10, null=True)),
                ('min_order_value', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo para aplicar la promoción', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('max_uses', models.IntegerField(blank=True, help_text='Dejar vacío para usos ilimitados', null=True)),
                ('current_uses', models.IntegerField(default=0, help_text='Usos actuales (se incrementa automáticamente)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Dejar vacío para aplicar a todas', to='products.category')),
                ('products', models.ManyToManyField(blank=True, help_text='Dejar vacío para aplicar a todos', to='products.product')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
