# Generated by Django 4.2 on 2026-05-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
