# Generated by Django 4.2 on 2026-06-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_image'),
        ('promotions', '0003_allow_null_codes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Usar para promos automáticas por categoría', to='products.category'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='products',
            field=models.ManyToManyField(blank=True, help_text='Usar para promos automáticas sobre productos concretos', to='products.product'),
        ),
    ]
