# Generated by Django 4.2 on 2026-05-15 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='order_id',
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='checkout_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='external_reference',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='payment_method',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='provider_payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='transaction_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='provider',
            field=models.CharField(choices=[('mercado_pago', 'Mercado Pago'), ('cash', 'Efectivo')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('cancelled', 'Cancelado'), ('refunded', 'Reintegrado')], default='pending', max_length=50),
        ),
    ]
