# Generated by Django 4.2 on 2026-05-15 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Josephine Shop', max_length=200)),
                ('contact_whatsapp', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
