# Generated by Django 4.2 on 2026-06-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=100, unique=True)),
                ('text', models.TextField(blank=True)),
                ('description', models.CharField(blank=True, help_text='(admin only) short note about the purpose of this text', max_length=255)),
            ],
            options={
                'verbose_name': 'Site text',
                'verbose_name_plural': 'Site texts',
            },
        ),
    ]
