# Generated by Django 4.2 on 2026-05-28 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_customer_email_productreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='productreservation',
            name='locked_by_order',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productreservation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
    ]
