# Generated by Django 4.2 on 2026-06-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_variant_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('rejected', 'Rechazada'), ('processing', 'Empaquetando'), ('shipped', 'En Camino'), ('delivered', 'Finalizado'), ('cancelled', 'Cancelado')], default='pending', max_length=30),
        ),
    ]
