# Generated by Django 4.2 on 2026-06-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_province',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
