# Generated by Django 4.2 on 2026-05-20 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_color_hex'),
    ]

    def copy_product_colors(apps, schema_editor):
        Product = apps.get_model('products', 'Product')
        ProductColor = apps.get_model('products', 'ProductColor')

        for product in Product.objects.all():
            color_hex = (getattr(product, 'color_hex', '') or '').strip()
            if color_hex:
                ProductColor.objects.get_or_create(product_id=product.id, color_hex=color_hex)

    operations = [
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_hex', models.CharField(max_length=7)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'color_hex')},
            },
        ),
        migrations.RunPython(copy_product_colors, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='color_hex',
        ),
    ]
