from django.urls import path
from . import views

from .views import (
    cart_view,
    admin_category_new,
    admin_category_edit,
    admin_category_delete,
    admin_categories_list,
    admin_panel,
    admin_site_texts,
    admin_orders,
    admin_promotion_new,
    admin_promotion_edit,
    admin_promotion_delete,
    admin_promotions_list,
    admin_product_new,
    admin_product_edit,
    admin_product_delete,
    admin_products_list,
    catalog,
    checkout_view,
    index,
    login_view,
    logout_view,
    password_reset_confirm_view,
    password_reset_request_view,
    order_success,
    order_lookup,
    product_detail,
    register_view,
)

app_name = 'web'

urlpatterns = [
    path('', index, name='index'),
    path('catalogo/', catalog, name='catalog'),
    path('producto/<int:pk>/', product_detail, name='product_detail'),
    path('carrito/', cart_view, name='cart'),
    path('checkout/', checkout_view, name='checkout'),
    path('consultar-pedidos/', order_lookup, name='order_lookup'),
    path('pedido/<int:order_id>/', order_success, name='order_success'),
    path('ingresar/', login_view, name='login'),
    path('recuperar-contrasena/', password_reset_request_view, name='password_reset_request'),
    path('recuperar-contrasena/<str:uidb64>/<str:token>/', password_reset_confirm_view, name='password_reset_confirm'),
    path('registrarse/', register_view, name='register'),
    path('salir/', logout_view, name='logout'),
    path('panel/', admin_panel, name='admin_panel'),
    path('panel/pedidos/', admin_orders, name='admin_orders'),
    path('panel/textos/', admin_site_texts, name='admin_site_texts'),
    path('panel/productos/', admin_products_list, name='admin_products_list'),
    path('panel/producto-nuevo/', admin_product_new, name='admin_product_new'),
    path('panel/producto/<int:pk>/editar/', admin_product_edit, name='admin_product_edit'),
    path('panel/producto/<int:pk>/eliminar/', admin_product_delete, name='admin_product_delete'),
    path('panel/categorias/', admin_categories_list, name='admin_categories_list'),
    path('panel/categoria-nueva/', admin_category_new, name='admin_category_new'),
    path('panel/categoria/<int:pk>/editar/', admin_category_edit, name='admin_category_edit'),
    path('panel/categoria/<int:pk>/eliminar/', admin_category_delete, name='admin_category_delete'),
    path('panel/promociones/', admin_promotions_list, name='admin_promotions_list'),
    path('panel/promocion-nueva/', admin_promotion_new, name='admin_promotion_new'),
    path('panel/promocion/<int:pk>/editar/', admin_promotion_edit, name='admin_promotion_edit'),
    path('panel/promocion/<int:pk>/eliminar/', admin_promotion_delete, name='admin_promotion_delete'),
    path('panel/drops/', views.admin_drops_list, name='admin_drops_list'),
    path('panel/drops/nuevo/', views.admin_drop_new, name='admin_drop_new'),
    path('panel/drops/<int:pk>/editar/', views.admin_drop_edit, name='admin_drop_edit'),
    path('panel/drops/<int:pk>/eliminar/', views.admin_drop_delete, name='admin_drop_delete'),
]
